# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: vpro-installer-generator
description: Vpro Installer Generator for Edge Infrastructure Manager
type: application
version: 1.0.0
appVersion: "1.0.0"
annotations: {}
maintainers:
  - name: Edge Infrastructure Manager Team
home: edge-orchestrator.intel.com
