# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

{{- if .Values.traefikReverseProxy.enabled }}

apiVersion: {{ .Values.traefikApiGroup }}
kind: Middleware
metadata:
  name: {{ include "rps.fullname" . }}-websocket-server
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  headers:
    sslProxyHeaders:
      X-Forwarded-Proto: "https"
    customRequestHeaders:
      Host: {{ .Values.traefikReverseProxy.host.grpc.name }}
      Connection: "Upgrade"
      Upgrade: "websocket"

---
apiVersion: {{ .Values.traefikApiGroup }}
kind: IngressRoute
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: "Host(`{{ .Values.traefikReverseProxy.host.grpc.name }}`) && PathPrefix(`/`)"
    kind: Rule
    middlewares:
       - name: {{ include "rps.fullname" . }}-websocket-server
    services:
      - name: {{ include "rps.fullname" . }}
        port: {{ .Values.service.websocketServerport }}
        scheme: http
        namespace: {{ .Release.Namespace }}
  - match: Host(`{{ required "A valid rpsApiHostname entry required!" .Values.rpsIngressRoute.rpsApiHostname }}`) && PathRegexp(`^/v1/projects/[^/]+/(dm/amt/admin/domains)(/.*)?$`)
    kind: Rule
    priority: 50
    middlewares:
       - name: validate-jwt
       - name: secure-headers
    services:
      - name: {{ required "A valid rpsServiceName entry required!" .Values.rpsIngressRoute.rpsServiceName }}
        port: {{ required "A valid rpsServicePort entry required!" .Values.rpsIngressRoute.rpsServicePort }}
        scheme: http
        namespace: {{ required "A valid rpsServiceNamespace entry required!" .Values.rpsIngressRoute.rpsServiceNamespace }}
  - match: Host(`{{ required "A valid rpsApiHostname entry required!" .Values.rpsIngressRoute.rpsApiHostname }}`) && PathPrefix(`/api/v1`)
    kind: Rule
    priority: 40
    middlewares:
       - name: validate-jwt
       - name: secure-headers
    services:
      - name: {{ required "A valid rpsServiceName entry required!" .Values.rpsIngressRoute.rpsServiceName }}
        port: {{ required "A valid rpsServicePort entry required!" .Values.rpsIngressRoute.rpsServicePort }}
        scheme: http
        namespace: {{ required "A valid rpsServiceNamespace entry required!" .Values.rpsIngressRoute.rpsServiceNamespace }}
  - match: "Host(`{{ .Values.traefikReverseProxy.host.webport.name }}`) && PathPrefix(`/`)"
    kind: Rule
    middlewares:
       - name: validate-jwt
    services:
      - name: {{ include "rps.fullname" . }}
        port: {{ .Values.service.webapiport }}
        scheme: http
        namespace: {{ .Release.Namespace }}
  tls:
  {{- if .Values.traefikReverseProxy.tlsOption }}
    options:
      name: {{ .Values.traefikReverseProxy.tlsOption }}
      namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
  {{- end }}
    secretName: {{ .Values.traefikReverseProxy.secretName }}
{{- end }}
