# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

{{- if .Values.traefikReverseProxy.enabled }}

# HTTP IngressRoute
apiVersion: {{ .Values.traefikApiGroup }}
kind: IngressRoute
metadata:
  name: "{{ .Values.ingress.name }}"
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`{{ required "A valid mpsApiHostname entry required!" .Values.mpsIngressRoute.mpsApiHostname }}`) && PathRegexp(`^/v1/projects/[^/]+/(dm/amt/generalSettings|dm/devices)(/.*)?$`)
    kind: Rule
    priority: 50
    middlewares:
       - name: validate-jwt
       - name: secure-headers
    services:
      - name: {{ required "A valid mpsServiceName entry required!" .Values.mpsIngressRoute.mpsServiceName }}
        port: {{ required "A valid mpsServicePort entry required!" .Values.mpsIngressRoute.mpsServicePort }}
        scheme: http
        namespace: {{ required "A valid mpsServiceNamespace entry required!" .Values.mpsIngressRoute.mpsServiceNamespace }}
  - match: Host(`{{ required "A valid mpsApiHostname entry required!" .Values.mpsIngressRoute.mpsApiHostname }}`) && PathPrefix(`/api/v1`)
    kind: Rule
    priority: 40
    middlewares:
       - name: validate-jwt
       - name: secure-headers
    services:
      - name: {{ required "A valid mpsServiceName entry required!" .Values.mpsIngressRoute.mpsServiceName }}
        port: {{ required "A valid mpsServicePort entry required!" .Values.mpsIngressRoute.mpsServicePort }}
        scheme: http
        namespace: {{ required "A valid mpsServiceNamespace entry required!" .Values.mpsIngressRoute.mpsServiceNamespace }}
  - match: "Host(`{{ .Values.traefikReverseProxy.host.webport.name}}`) && PathPrefix(`/`)"
    kind: Rule
    middlewares:
       - name: validate-jwt
    services:
      - name: {{ include "mps.fullname" . }}
        port: {{ .Values.service.webapiport }}
        scheme: http
        namespace: {{ .Release.Namespace }}
  tls:
  {{- if .Values.traefikReverseProxy.tlsOption }}
    options:
      name: {{ .Values.traefikReverseProxy.tlsOption }}
      namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
  {{- end }}
    secretName: {{ .Values.traefikReverseProxy.secretName }}

---
# TCP IngressRoute
apiVersion: {{ .Values.traefikApiGroup }}
kind: IngressRouteTCP
metadata:
  name: "{{ .Values.ingress.name }}"
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  entryPoints:
  - tcpamt
  routes:
  - match: HostSNI(`*`)
    services:
      - name: {{ include "mps.fullname" . }}
        port: {{ .Values.service.ciraport }}
        namespace: {{ .Release.Namespace }}
  tls:
    passthrough: true
{{- end }}
