# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceAccount.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRoleName}}
rules:
  - apiGroups: ["tinkerbell.org"]
    resources: ["hardware", "hardware/status"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["tinkerbell.org"]
    resources: ["templates", "templates/status"]
    verbs: ["get", "list", "watch", "create", "delete", "deletecollection"]
  - apiGroups: ["tinkerbell.org"]
    resources: ["workflows", "workflows/status"] 
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
{{- end }}
