---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: batch/v1
kind: Job
metadata:
  name: credentials-{{ randAlphaNum 8 | lower }}
  {{- with .Values.jobAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "credentials.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "credentials.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName:  {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.curlImage.name }}:{{ .Values.curlImage.tag }}"
          imagePullPolicy: {{ .Values.curlImage.pullPolicy }}
          command: ["/bin/sh"]
          args: ["/onboard-credentials.sh", "{{ .Values.params.keycloakUrl }}", "{{ .Values.params.vaultUrl }}", "{{.Values.serviceAccount.name }}"]
          env:
            - name: ADMIN_USER
              value: "{{ .Values.keycloakAdmin.user }}"
            - name: ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.keycloakAdmin.passwordSecret.key }}
                  name: {{ .Values.keycloakAdmin.passwordSecret.name }}
            - name: ADMIN_CLIENT
              value: "{{ .Values.keycloakAdmin.client }}"
          volumeMounts:
            - mountPath: /onboard-credentials.sh
              subPath: onboard-credentials.sh
              name: credentials
      volumes:
        - name: credentials
          configMap:
            name: {{ include "credentials.name" . }}-script
            defaultMode: 0777

