# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# TODO: Clean up metrics kvm-manager has no metrics instrumented yet.
# Remove this serviceMonitor.
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kvm-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kvm-manager.selectorLabels" . | nindent 6 }}
{{- end }}
