# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: infra-external
description: Edge Infrastructure Manager External Umbrella Chart
type: application
version: "2.5.2"
appVersion: "2.5.2"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
dependencies:
  - name: loca-manager
    condition: import.loca-manager.enabled
    version: "2.17.0"
    repository: "file://../loca-manager"
  - name: loca-credentials
    condition: import.loca-credentials.enabled
    version: "1.2.0"
    repository: "file://../loca-credentials"
  - name: loca-metadata-manager
    condition: import.loca-metadata-manager.enabled
    version: "1.3.0"
    repository: "file://../loca-metadata"
  - name: loca-templates-manager
    condition: import.loca-templates-manager.enabled
    version: "1.3.0"
    repository: "file://../loca-templates-manager"
  - name: amt
    condition: import.amt.enabled
    version: "0.1.3"
    repository: "file://../amt"

