# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: remote-access-manager
description: Edge Infrastructure Manager Maintenance Manager
type: application
version: 1.28.0-dev
appVersion: "1.24.3"
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
