# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
{{- if eq .Values.params.passwordPolicy "static" }}
{{- $password := "" }}
{{- if .Values.params.password }}
  {{- $password = .Values.params.password }}
{{- else }}
  {{- /* Generate a random password with: uppercase, lowercase, digits, special chars, min 12 chars */ -}}
  {{- $upper := "ABCDEFGHIJKLMNOPQRSTUVWXYZ" }}
  {{- $lower := "abcdefghijklmnopqrstuvwxyz" }}
  {{- $digits := "0123456789" }}
  {{- $special := "!@#$%^&*" }}
  {{- $all := printf "%s%s%s%s" $upper $lower $digits $special }}
  {{- /* Ensure at least one char from each category */ -}}
  {{- $randUpper := substr 0 1 (shuffle $upper) }}
  {{- $randLower := substr 0 1 (shuffle $lower) }}
  {{- $randDigit := substr 0 1 (shuffle $digits) }}
  {{- $randSpecial := substr 0 1 (shuffle $special) }}
  {{- /* Generate additional 8 random characters */ -}}
  {{- $randExtra := substr 0 8 (shuffle $all) }}
  {{- $password = printf "%s%s%s%s%s" $randUpper $randLower $randDigit $randSpecial $randExtra | shuffle }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dm-manager.fullname" . }}-amt-password
  labels:
    {{- include "dm-manager.labels" . | nindent 4 }}
  annotations:
    # Force recreation on each helm upgrade to generate new password
    "helm.sh/resource-policy": replace
    "checksum/config": {{ $password | sha256sum }}
type: Opaque
data:
  # Base64 encoded AMT password (auto-generated if not provided)
  amt-password: {{ $password | b64enc | quote }}
{{- end }}
