# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: infra-onboarding
description: Edge Infrastructure Manager Onboarding Umbrella Chart
type: application
version: "1.33.3"
appVersion: "1.33.3"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
dependencies:
  - name: onboarding-manager
    condition: import.onboarding-manager.enabled
    version: "1.39.10"
    repository: "file://../onboarding-manager"
  - name: dkam
    condition: import.dkam.enabled
    version: "1.30.1"
    repository: "file://../dkam"
  - name: tinkerbell
    condition: import.tinkerbell.enabled
    version: "2.12.0"
    repository: "file://../tinkerbell"
  - name: infra-config
    condition: import.infra-config.enabled
    version: "0.6.3"
    repository: "file://../infra-config"
  - name: pxe-server
    condition: import.pxe-server.enabled
    version: "0.1.2"
    repository: "file://../pxe-server"
