# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: infra-onboarding
description: Edge Infrastructure Manager Onboarding Umbrella Chart
type: application
version: "1.35.5"
appVersion: "1.34.6"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
dependencies:
  - name: onboarding-manager
    condition: import.onboarding-manager.enabled
    version: "1.40.3"
    repository: "file://../onboarding-manager"
  - name: dkam
    condition: import.dkam.enabled
    version: "1.31.0"
    repository: "file://../dkam"
  - name: tinkerbell
    condition: import.tinkerbell.enabled
    version: "2.14.0"
    repository: "file://../tinkerbell"
  - name: infra-config
    condition: import.infra-config.enabled
    version: "0.7.1"
    repository: "file://../infra-config"
  - name: pxe-server
    condition: import.pxe-server.enabled
    version: "0.2.0-dev"
    repository: "file://../pxe-server"
