# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v2
name: infra-core
description: Edge Infrastructure Manager Core Umbrella Chart
type: application
version: "2.19.0-dev"
appVersion: "2.19.0-dev"
annotations: {}
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
dependencies:
  - name: api
    condition: import.api.enabled
    version: "1.32.1"
    repository: "file://../api"
  - name: apiv2
    condition: import.apiv2.enabled
    version: "2.5.1"
    repository: "file://../apiv2"
  - name: exporter
    condition: import.exporter.enabled
    version: "1.23.0"
    repository: "file://../exporter"
  - name: inventory
    condition: import.inventory.enabled
    version: "2.29.3"
    repository: "file://../inventory"
  - name: credentials
    condition: import.credentials.enabled
    version: "1.8.1"
    repository: "file://../credentials"
  - name: tenant-controller
    condition: import.tenant-controller.enabled
    version: "0.24.2"
    repository: "file://../tenant-controller"
  - name: tenant-config
    condition: import.tenant-config.enabled
    version: "0.1.2"
    repository: "file://../tenant-config"
