# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
# NOTE this is used only in the dev environment
{{- if .Values.postgresql.pod.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secrets }}
stringData:
  PGUSER: "admin"
  PGPASSWORD: "<REPLACE_WITH_PASSWORD>"
  PGDATABASE: "postgres"
  PGPORT: "5432"
  PGHOST: "inventory-postgresql-0.inventory-postgresql"
{{- end }}
