# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

apiVersion: v2
name: amt
description: Edge Infrastructure Manager AMT
type: application
version: 0.0.7
appVersion: "0.0.7"
home: edge-orchestrator.intel.com
maintainers:
  - name: Edge Infrastructure Manager Team
dependencies:
  - name: mps
    version: "0.0.7"
    condition: import.mps.enabled
    repository: "file://charts/mps"
  - name: rps
    version: "0.0.6"
    condition: import.rps.enabled
    repository: "file://charts/rps"
  - name: dm-manager
    version: "0.0.2"
    condition: import.dm-manager.enabled
    repository: "file://charts/dm-manager"
