# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---

global:
  registry:
    name: null
    imagePullSecrets:
      - name: ""

import:
  mps:
    enabled: true
  rps:
    enabled: true
  dm-manager:
    enabled: true
  kvm-manager:
    enabled: false

mps:
  postgresql:
    type: "local"
  image:
    registry:
      name: docker.io/
    repository: intel/oact-mps
    tag: v2.14.2
    pullPolicy: IfNotPresent
    # Image specific takes precedence
    # registry:
    #   name: null
    #   imagePullSecrets:
    #     - name: ""

rps:
  postgresql:
    type: "local"
  image:
    registry:
      name: docker.io/
    repository: intel/oact-rps
    tag: v2.26.0
    pullPolicy: IfNotPresent
    # Image specific takes precedence
    # registry:
    #   name: null
    #   imagePullSecrets:
    #     - name: ""

kvm-manager:
  image:
    repository: infra/kvm-manager
    pullPolicy: IfNotPresent
  serviceArgs:
    inventoryAddress: "inventory.orch-infra.svc.cluster.local:50051"
    mpsAddress: "http://mps.orch-infra.svc.cluster.local:3000"
    mpsDomain: ""
    traceURL: ""
    oamServerAddress: ""
  tracing:
    enabled: false
