---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v1
kind: Service
metadata:
  name: {{ include "attestationstatusmgr-manager.fullname" . }}
  labels:
    {{- include "attestationstatusmgr-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.attestationstatusmgr.name }}
      port: {{ .Values.service.attestationstatusmgr.port }}
      targetPort: {{ .Values.service.attestationstatusmgr.port }}
      protocol: TCP
  {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  {{- end }}
  selector:
    {{- include "attestationstatusmgr-manager.selectorLabels" . | nindent 4 }}
---
{{- if .Values.traefikReverseProxy.enabled }}
apiVersion: {{ .Values.traefikApiGroup }}
kind: IngressRoute
metadata:
  name: "attest-api-grpc-node"
  namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
spec:
  entryPoints: # We listen to requests coming from ports 443
    - websecure
  routes:
    - match: {{ required "A valid updateNodeMatchHost entry required!" .Values.traefikReverseProxy.host.grpc.name }} && PathPrefix(`/`)
      kind: Rule
      middlewares:
        - name: validate-jwt
      services:
        - name: {{ include "attestationstatusmgr-manager.fullname" . }}
          port: {{ .Values.service.attestationstatusmgr.port }}
          scheme: h2c
          namespace: {{ .Release.Namespace }}
  tls:
    # Use the secret generated by cert-manager that resides in orch-gateway namespace
    secretName: {{ .Values.traefikReverseProxy.secretName }}
{{- if .Values.traefikReverseProxy.tlsOption }}
    options:
      name: {{ .Values.traefikReverseProxy.tlsOption }}
      namespace: {{ .Values.traefikReverseProxy.gatewayNamespace }}
{{- end }}
{{- end }}
